language: python
python:
  - "3.6"

os:
  - osx

# command to install dependencies
install:
  - pip install -r requirements.txt

cache: pip
script:
  - python tests/AnswerTest.py
  - python tests/ImageTest.py