language: python
python:
  - "3.6"

os:
  - osx

# command to install dependencies
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list python &>/dev/null || brew install python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list python3 &>/dev/null || brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pyenv-virtualenv; fi

install:
  - pip3 install -r requirements.txt

cache: pip
script:
  - python tests/AnswerTest.py
  - python tests/ImageTest.py

matrix:
  include:
    - os: osx
      language: generic
      env: TOXENV=py36
  fast_finish: true