language: python
python:
  - "3.6"

os:
  - osx

# command to install dependencies
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list python3 &>/dev/null; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python3; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pyenv-virtualenv; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python3 --version; fi

install:
  - python3 -m pip install -r requirements.txt

cache: pip
script:
  - python tests/AnswerTest.py
  - python tests/ImageTest.py

matrix:
  include:
    - os: osx
      language: generic
      env: TOXENV=py36
  fast_finish: true